#include "gettid.h"
#include "siginfo_t.h"
#include "sigval_t.h"

#include "struct-linux_dirent.h"
#include "struct-pt_regs.h"
#include "struct-rusage.h"
#include "struct-stat.h"
#include "struct-user_desc.h"
#include "struct-utsname.h"

#include "_syscall_0.h"
#include "_syscall_1.h"
#include "_syscall_2.h"
#include "_syscall_3.h"
#include "_syscall_4.h"
#include "_syscall_5.h"
#include "_syscall_6.h"
