// For internal testing only.

#pragma clang diagnostic ignored "-Wunused-function"

#include "EXIT_FAILURE.h"
#include "EXIT_SUCCESS.h"

#include "INT8_C.h"
#include "INT16_C.h"
#include "INT32_C.h"
#include "INT64_C.h"

#include "INT8_MAX.h"
#include "INT16_MAX.h"
#include "INT32_MAX.h"
#include "INT64_MAX.h"

#include "INT8_MIN.h"
#include "INT16_MIN.h"
#include "INT32_MIN.h"
#include "INT64_MIN.h"

#include "INTMAX_MAX.h"
#include "INTMAX_MIN.h"

#include "INTPTR_MAX.h"
#include "INTPTR_MIN.h"

#include "INT_FAST8_MAX.h"
#include "INT_FAST16_MAX.h"
#include "INT_FAST32_MAX.h"
#include "INT_FAST64_MAX.h"

#include "INT_FAST8_MIN.h"
#include "INT_FAST16_MIN.h"
#include "INT_FAST32_MIN.h"
#include "INT_FAST64_MIN.h"

#include "INT_LEAST8_MAX.h"
#include "INT_LEAST16_MAX.h"
#include "INT_LEAST32_MAX.h"
#include "INT_LEAST64_MAX.h"

#include "INT_LEAST8_MIN.h"
#include "INT_LEAST16_MIN.h"
#include "INT_LEAST32_MIN.h"
#include "INT_LEAST64_MIN.h"

#include "INT_MAX.h"

#include "NULL.h"

#include "PTRDIFF_MAX.h"
#include "PTRDIFF_MIN.h"

#include "RAND_MAX.h"

#include "SIG_ATOMIC_MAX.h"
#include "SIG_ATOMIC_MIN.h"

#include "SIZE_MAX.h"

#include "STDERR_FILENO.h"
#include "STDIN_FILENO.h"
#include "STDOUT_FILENO.h"

#include "UINT8_C.h"
#include "UINT16_C.h"
#include "UINT32_C.h"
#include "UINT64_C.h"

#include "UINT8_MAX.h"
#include "UINT16_MAX.h"
#include "UINT32_MAX.h"
#include "UINT64_MAX.h"

#include "UINTMAX_MAX.h"

#include "UINTPTR_MAX.h"

#include "UINT_FAST8_MAX.h"
#include "UINT_FAST16_MAX.h"
#include "UINT_FAST32_MAX.h"
#include "UINT_FAST64_MAX.h"

#include "UINT_LEAST8_MAX.h"
#include "UINT_LEAST16_MAX.h"
#include "UINT_LEAST32_MAX.h"
#include "UINT_LEAST64_MAX.h"

#include "WCHAR_MAX.h"
#include "WCHAR_MIN.h"

#include "WINT_MAX.h"
#include "WINT_MIN.h"

#include "_exit.h"
#include "abs.h"
#include "alignas.h"
#include "alignof.h"
#include "alloca.h"
#include "bool.h"
#include "char16_t.h"
#include "char32_t.h"
#include "div_t.h"
#include "false.h"
#include "int8_t.h"
#include "int16_t.h"
#include "int32_t.h"
#include "int64_t.h"
#include "int_fast8_t.h"
#include "int_fast16_t.h"
#include "int_fast32_t.h"
#include "int_fast64_t.h"
#include "int_least8_t.h"
#include "int_least16_t.h"
#include "int_least32_t.h"
#include "int_least64_t.h"
#include "intmax_t.h"
#include "intptr_t.h"
#include "ldiv_t.h"
#include "lldiv_t.h"
#include "memcpy.h"
#include "noreturn.h"
#include "offsetof.h"
#include "ptrdiff_t.h"
#include "size_t.h"
#include "ssize_t.h"
#include "static_assert.h"
#include "strcmp.h"
#include "strlen.h"
#include "true.h"
#include "uint8_t.h"
#include "uint16_t.h"
#include "uint32_t.h"
#include "uint64_t.h"
#include "uint_fast8_t.h"
#include "uint_fast16_t.h"
#include "uint_fast32_t.h"
#include "uint_fast64_t.h"
#include "uint_least8_t.h"
#include "uint_least16_t.h"
#include "uint_least32_t.h"
#include "uint_least64_t.h"
#include "uintmax_t.h"
#include "uintptr_t.h"
#include "wchar_t.h"
#include "wint_t.h"
