#ifndef INT16_MIN

#include "__SIGNED_INTEGER_REPRESENTATION.h"

#if __SIGNED_INTEGER_REPRESENTATION == __SIGNED_INTEGER_REPRESENTATION_TWOS_COMPLEMENT
#  include "INT16_MAX.h"
#  define INT16_MIN (-INT16_MAX - 1)
#else
#  error
#endif

#endif
