#pragma once

#include "__SIGNED_INTEGER_REPRESENTATION.h"

#if __SIGNED_INTEGER_REPRESENTATION == __SIGNED_INTEGER_REPRESENTATION_TWOS_COMPLEMENT
#  include "INT_LEAST8_MAX.h"
#  define INT_LEAST8_MIN (-INT_LEAST8_MAX - 1)
#else
#  error
#endif
