#ifndef INT_FAST32_MIN

#include "__SIGNED_INTEGER_REPRESENTATION.h"

#if __SIGNED_INTEGER_REPRESENTATION == __SIGNED_INTEGER_REPRESENTATION_TWOS_COMPLEMENT
#  include "INT_FAST32_MAX.h"
#  define INT_FAST32_MIN (-INT_FAST32_MAX - 1)
#else
#  error
#endif

#endif
