#ifndef INT_MIN

#include "../__SIGNED_INTEGER_REPRESENTATION.h"

#if __SIGNED_INTEGER_REPRESENTATION == __SIGNED_INTEGER_REPRESENTATION_TWOS_COMPLEMENT
#  include "INT_MAX.h"
#  define INT_MIN (-INT_MAX - 1)
#else
#  error
#endif

#endif
