#ifndef INTMAX_MIN

#include "../__SIGNED_INTEGER_REPRESENTATION.h"

#if __SIGNED_INTEGER_REPRESENTATION == __SIGNED_INTEGER_REPRESENTATION_TWOS_COMPLEMENT
#  include "INTMAX_MAX.h"
#  define INTMAX_MIN (-INTMAX_MAX - 1)
#else
#  error
#endif

#endif
