#pragma once

#include "WCONTINUED.h"
#include "WEXITED.h"
// WEXITSTATUS
// WIFCONTINUED
// WIFEXITED
// WIFSIGNALED
// WIFSTOPPED
#include "WNOHANG.h"
#include "WNOWAIT.h"
// WSTOPPED
// WSTOPSIG
// WTERMSIG
// WUNTRACED
#include "../types/id_t.h"
#include "idtype_t.h"
#include "../types/pid_t.h"
#include "../signal/siginfo_t.h"
#include "../resource/struct-rusage.h"
// wait
// waitid
// waitpid
