#include "__POINTER_WIDTH__.h"

#include "__builtin_addressof.h"
#include "__builtin_assume.h"
#include "__builtin_assume_aligned.h"
#include "__builtin_bswap32.h"
#include "__builtin_bswap64.h"
#include "__builtin_constant_p.h"
#include "__builtin_expect.h"
#include "__builtin_unreachable.h"
