#include "NORETURN.h"
#include "NOTHROW.h"
#include "REINTERPRET_CAST.h"
#include "STATIC_CAST.h"

#include "__builtin_addressof.h"
#include "__builtin_assume.h"
#include "__builtin_assume_aligned.h"
#include "__builtin_constant_p.h"
#include "__builtin_expect.h"
#include "__builtin_unreachable.h"
