#pragma once

#include "c/E2BIG.h"
#include "c/EACCES.h"
#include "c/EADDRINUSE.h"
#include "c/EADDRNOTAVAIL.h"
#include "c/EAFNOSUPPORT.h"
#include "c/EAGAIN.h"
#include "c/EALREADY.h"
#include "c/EBADF.h"
#include "c/EBADMSG.h"
#include "c/EBUSY.h"
#include "c/ECANCELED.h"
#include "c/ECHILD.h"
#include "c/ECONNABORTED.h"
#include "c/ECONNREFUSED.h"
#include "c/ECONNRESET.h"
#include "c/EDEADLK.h"
#include "c/EDESTADDRREQ.h"
#include "c/EDOM.h"
#include "c/EDQUOT.h"
#include "c/EEXIST.h"
#include "c/EFAULT.h"
#include "c/EFBIG.h"
#include "c/EHOSTUNREACH.h"
#include "c/EIDRM.h"
#include "c/EILSEQ.h"
#include "c/EINPROGRESS.h"
#include "c/EINTR.h"
#include "c/EINVAL.h"
#include "c/EIO.h"
#include "c/EISCONN.h"
#include "c/EISDIR.h"
#if defined(__linux__)
#  include "c/ELIBBAD.h"
#endif
#include "c/ELOOP.h"
#include "c/EMFILE.h"
#include "c/EMLINK.h"
#include "c/EMSGSIZE.h"
#include "c/EMULTIHOP.h"
#include "c/ENAMETOOLONG.h"
#include "c/ENETDOWN.h"
#include "c/ENETRESET.h"
#include "c/ENETUNREACH.h"
#include "c/ENFILE.h"
#include "c/ENOBUFS.h"
#include "c/ENODATA.h" // [XSR]
#include "c/ENODEV.h"
#include "c/ENOENT.h"
#include "c/ENOEXEC.h"
#include "c/ENOLCK.h"
#include "c/ENOLINK.h"
#include "c/ENOMEM.h"
#include "c/ENOMSG.h"
#include "c/ENOPROTOOPT.h"
#include "c/ENOSPC.h"
#include "c/ENOSR.h" // [XSR]
#include "c/ENOSTR.h" // [XSR]
#include "c/ENOSYS.h"
#include "c/ENOTBLK.h" // Nonstandard
#include "c/ENOTCONN.h"
#include "c/ENOTDIR.h"
#include "c/ENOTEMPTY.h"
#include "c/ENOTRECOVERABLE.h"
#include "c/ENOTSOCK.h"
#include "c/ENOTSUP.h"
#include "c/ENOTTY.h"
#include "c/ENXIO.h"
#include "c/EOPNOTSUPP.h"
#include "c/EOVERFLOW.h"
#include "c/EOWNERDEAD.h"
#include "c/EPERM.h"
#include "c/EPIPE.h"
#include "c/EPROTO.h"
#include "c/EPROTONOSUPPORT.h"
#include "c/EPROTOTYPE.h"
#include "c/ERANGE.h"
#include "c/EROFS.h"
#include "c/ESPIPE.h"
#include "c/ESRCH.h"
// ESTALE (reserved)
#include "c/ETIME.h" // [XSR]
#include "c/ETIMEDOUT.h"
#include "c/ETXTBSY.h"
#include "c/EWOULDBLOCK.h"
#include "c/EXDEV.h"
