#pragma once

#include "WCONTINUED.h"
#include "WEXITED.h"
// WEXITSTATUS
// WIFCONTINUED
// WIFEXITED
// WIFSIGNALED
// WIFSTOPPED
#include "WNOHANG.h"
#include "WNOWAIT.h"
// WSTOPPED
// WSTOPSIG
// WTERMSIG
// WUNTRACED
#include "id_t.h"
#include "idtype_t.h"
#include "pid_t.h"
#include "siginfo_t.h"
#include "struct-rusage.h"
// wait
// waitid
// waitpid
